const SHOPPING_STORE_KEY = 'shoppingStore';
const AUTH_KEY = 'auth';
const NAVIGATION_STATE_KEY = 'NAVIGATION_STATE_V1';
const TOTAL_ITEMS = 200;

export { SHOPPING_STORE_KEY, AUTH_KEY, NAVIGATION_STATE_KEY, TOTAL_ITEMS };
